# fly.toml app configuration file generated for bluffer on 2026-05-23T09:36:19-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bluffer'
primary_region = 'sjc'

[build]

[env]
  APP_BASE_URL = 'https://bluffer.fly.dev'
  DB_PATH = '/data/bluffer.db'
  HOST = '0.0.0.0'
  PORT = '3000'

[[mounts]]
  source = 'bluffer_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
